{
 "title": "LiveStream2",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1s",
 "panels": [
  {
   "title": "Acceleration",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "accMS2" } },
   "targets": [
    {
     "query": "from(bucket: \"can_bucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"acceleration\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> filter(fn: (r) => r[\"host\"] == \"host1\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Altitude",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "lengthm" } },
   "targets": [
    {
     "query": "from(bucket: \"can_bucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"altitude\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> filter(fn: (r) => r[\"host\"] == \"host1\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Roll rate",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "rotdegs" } },
   "targets": [
    {
     "query": "from(bucket: \"can_bucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"roll_rate\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> filter(fn: (r) => r[\"host\"] == \"host1\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 0 },
   "options": {
    "content": "<!-- <img src=\"/public/custom_assets/hypower_logo.png\" alt=\"hypower_logo\">\n<img src=\"/public/custom_assets/uob_logo.png\" alt=\"uob_logo\"> -->\n\n<img src=\"/public/custom_assets/hypower_logo.png\" alt=\"Hypower Logo\" width=\"250\" height=\"auto\">\n<br/>\n<img src=\"/public/custom_assets/uob_logo.png\" alt=\"UOB Logo\" width=\"250\" height=\"auto\" style=\"background-color:white;\">\n<br/>\n<br/>\n<h6 id=\"date\"></h6>\n\n<script>\n  var now = new Date();\n  var datetime = now.toLocaleString();\n  document.getElementById(\"date\").innerHTML = `Date: ${datetime.split(',')[1]}`;\n</script>"
   }
  },
  {
   "title": "Acceleration",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "accMS2" } },
   "targets": [
    {
     "query": "from(bucket: \"can_bucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"acceleration\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> filter(fn: (r) => r[\"host\"] == \"host1\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Latitude",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "degree" } },
   "targets": [
    {
     "query": "from(bucket: \"can_bucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"latitude\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> filter(fn: (r) => r[\"host\"] == \"host1\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Longitude",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "degree" } },
   "targets": [
    {
     "query": "from(bucket: \"can_bucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"longitude\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> filter(fn: (r) => r[\"host\"] == \"host1\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Battery Voltage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {}
   ]
  },
  { "title": "Insert test", "type": "volkovlabs-form-panel", "gridPos": { "h": 5, "w": 8, "x": 0, "y": 10 } },
  {
   "title": "Roll position",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 14, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "degree" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } }
  },
  {
   "title": "Roll Rate",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 17, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "rotdegs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } }
  },
  { "title": "Raw Telemetry", "type": "table", "gridPos": { "h": 11, "w": 4, "x": 20, "y": 12 } },
  {
   "title": "3D model",
   "type": "lucasbremond-satellitevisualizer-panel",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "targets": [
    {
     "query": "last_timestamp = from(bucket: \"can_bucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"longitude\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> filter(fn: (r) => r[\"host\"] == \"host1\")\n  |> last()\n  |> map(fn: (r) => ({ r with _value: r[\"_time\"] })) // Convert _time to _value\n  |> keep(columns: [\"_value\"]) // Keep only _value column\n  |> yield()\n\nlongitude = from(bucket: \"can_bucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"longitude\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> filter(fn: (r) => r[\"host\"] == \"host1\")\n  |> last()\n\nlatitude = from(bucket: \"can_bucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"latitude\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> filter(fn: (r) => r[\"host\"] == \"host1\")\n  |> last()\n\naltitude = from(bucket: \"can_bucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"altitude\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> filter(fn: (r) => r[\"host\"] == \"host1\")\n  |> last()\n\nquaternion_q0 = from(bucket: \"can_bucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"q_x\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> filter(fn: (r) => r[\"host\"] == \"host1\")\n  |> last()\n\nquaternion_q1 = from(bucket: \"can_bucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"q_y\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> filter(fn: (r) => r[\"host\"] == \"host1\")\n  |> last()\n\nquaternion_q2 = from(bucket: \"can_bucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"q_z\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> filter(fn: (r) => r[\"host\"] == \"host1\")\n  |> last()\n  \nquaternion_q3 = from(bucket: \"can_bucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"q_s\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> filter(fn: (r) => r[\"host\"] == \"host1\")\n  |> last()\n\ntable1 = union(tables: [longitude, latitude, altitude, quaternion_q0, quaternion_q1, quaternion_q2, quaternion_q3])\n  |> pivot(rowKey: [\"host\"], columnKey: [\"_measurement\"], valueColumn: \"_value\")\n\n|> drop(columns: [\"host\", \"_field\", \"_start\", \"_stop\"])\n\n|> map(fn: (r) => ({\n    _time: r._time,\n    \"1\": r.longitude,\n    \"2\": r.latitude,\n    \"3\": r.altitude,\n    \"4\": r.q_x,\n    \"5\": r.q_y,\n    \"6\": r.q_z,\n    \"7\": r.q_s\n}))\n\n|> rename(columns: {\n    \"1\": \"1_Longitude\",\n    \"2\": \"2_Latitude\",\n    \"3\": \"3_Altitude\",\n    \"4\": \"4_x\",\n    \"5\": \"5_y\",\n    \"6\": \"6_z\",\n    \"7\": \"7_s\"\n})\n\n|> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Gyroscopes",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 23 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Accelerometers",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 23 },
   "targets": [
    {},
    {}
   ]
  },
  {
   "title": "Pitch + Yaw Attitude",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 29 },
   "targets": [
    {},
    {}
   ]
  },
  {
   "title": "Live camera feed",
   "type": "text",
   "gridPos": { "h": 17, "w": 15, "x": 5, "y": 29 },
   "options": {
    "content": "<iframe width=\"1000\" height=\"600\"\nsrc=\"http://localhost:1984/stream.html?src=obs_rtmp_server\">\n</iframe> "
   }
  },
  { "title": "Panel Title", "type": "geomap", "gridPos": { "h": 6, "w": 5, "x": 0, "y": 35 } }
 ]
}